const T = "https://flagcdn.com/w160/";
const IMAGE_URLS = {
  // Europe
  "Albania":                    T+"al.png",
  "Andorra":                    T+"ad.png",
  "Austria":                    T+"at.png",
  "Belarus":                    T+"by.png",
  "Belgium":                    T+"be.png",
  "Bosnia and Herzegovina":     T+"ba.png",
  "Bulgaria":                   T+"bg.png",
  "Croatia":                    T+"hr.png",
  "Cyprus":                     T+"cy.png",
  "Czech Republic":             T+"cz.png",
  "Denmark":                    T+"dk.png",
  "Estonia":                    T+"ee.png",
  "Finland":                    T+"fi.png",
  "France":                     T+"fr.png",
  "Georgia":                    T+"ge.png",
  "Germany":                    T+"de.png",
  "Greece":                     T+"gr.png",
  "Hungary":                    T+"hu.png",
  "Iceland":                    T+"is.png",
  "Ireland":                    T+"ie.png",
  "Italy":                      T+"it.png",
  "Kosovo":                     T+"xk.png",
  "Latvia":                     T+"lv.png",
  "Liechtenstein":              T+"li.png",
  "Lithuania":                  T+"lt.png",
  "Luxembourg":                 T+"lu.png",
  "Malta":                      T+"mt.png",
  "Moldova":                    T+"md.png",
  "Monaco":                     T+"mc.png",
  "Montenegro":                 T+"me.png",
  "Netherlands":                T+"nl.png",
  "North Macedonia":            T+"mk.png",
  "Norway":                     T+"no.png",
  "Poland":                     T+"pl.png",
  "Portugal":                   T+"pt.png",
  "Romania":                    T+"ro.png",
  "Russia":                     T+"ru.png",
  "San Marino":                 T+"sm.png",
  "Serbia":                     T+"rs.png",
  "Slovakia":                   T+"sk.png",
  "Slovenia":                   T+"si.png",
  "Spain":                      T+"es.png",
  "Sweden":                     T+"se.png",
  "Switzerland":                T+"ch.png",
  "Ukraine":                    T+"ua.png",
  "United Kingdom":             T+"gb.png",
  // North America
  "Antigua and Barbuda":        T+"ag.png",
  "Bahamas":                    T+"bs.png",
  "Barbados":                   T+"bb.png",
  "Belize":                     T+"bz.png",
  "Canada":                     T+"ca.png",
  "Costa Rica":                 T+"cr.png",
  "Cuba":                       T+"cu.png",
  "Dominica":                   T+"dm.png",
  "Dominican Republic":         T+"do.png",
  "El Salvador":                T+"sv.png",
  "Grenada":                    T+"gd.png",
  "Guatemala":                  T+"gt.png",
  "Haiti":                      T+"ht.png",
  "Honduras":                   T+"hn.png",
  "Jamaica":                    T+"jm.png",
  "Mexico":                     T+"mx.png",
  "Nicaragua":                  T+"ni.png",
  "Panama":                     T+"pa.png",
  "Saint Kitts and Nevis":      T+"kn.png",
  "Saint Lucia":                T+"lc.png",
  "Saint Vincent":              T+"vc.png",
  "Trinidad and Tobago":        T+"tt.png",
  "USA":                        T+"us.png",
  // South America
  "Argentina":                  T+"ar.png",
  "Bolivia":                    T+"bo.png",
  "Brazil":                     T+"br.png",
  "Chile":                      T+"cl.png",
  "Colombia":                   T+"co.png",
  "Ecuador":                    T+"ec.png",
  "Guyana":                     T+"gy.png",
  "Paraguay":                   T+"py.png",
  "Peru":                       T+"pe.png",
  "Suriname":                   T+"sr.png",
  "Uruguay":                    T+"uy.png",
  "Venezuela":                  T+"ve.png",
  // Asia
  "Afghanistan":                T+"af.png",
  "Armenia":                    T+"am.png",
  "Azerbaijan":                 T+"az.png",
  "Bahrain":                    T+"bh.png",
  "Bangladesh":                 T+"bd.png",
  "Bhutan":                     T+"bt.png",
  "Brunei":                     T+"bn.png",
  "Cambodia":                   T+"kh.png",
  "China":                      T+"cn.png",
  "India":                      T+"in.png",
  "Indonesia":                  T+"id.png",
  "Iran":                       T+"ir.png",
  "Iraq":                       T+"iq.png",
  "Israel":                     T+"il.png",
  "Japan":                      T+"jp.png",
  "Jordan":                     T+"jo.png",
  "Kazakhstan":                 T+"kz.png",
  "Kuwait":                     T+"kw.png",
  "Kyrgyzstan":                 T+"kg.png",
  "Laos":                       T+"la.png",
  "Lebanon":                    T+"lb.png",
  "Malaysia":                   T+"my.png",
  "Maldives":                   T+"mv.png",
  "Mongolia":                   T+"mn.png",
  "Myanmar":                    T+"mm.png",
  "Nepal":                      T+"np.png",
  "North Korea":                T+"kp.png",
  "Oman":                       T+"om.png",
  "Pakistan":                   T+"pk.png",
  "Palestine":                  T+"ps.png",
  "Philippines":                T+"ph.png",
  "Qatar":                      T+"qa.png",
  "Saudi Arabia":               T+"sa.png",
  "Singapore":                  T+"sg.png",
  "South Korea":                T+"kr.png",
  "Sri Lanka":                  T+"lk.png",
  "Syria":                      T+"sy.png",
  "Taiwan":                     T+"tw.png",
  "Tajikistan":                 T+"tj.png",
  "Thailand":                   T+"th.png",
  "Timor-Leste":                T+"tl.png",
  "Turkey":                     T+"tr.png",
  "Turkmenistan":               T+"tm.png",
  "UAE":                        T+"ae.png",
  "Uzbekistan":                 T+"uz.png",
  "Vietnam":                    T+"vn.png",
  "Yemen":                      T+"ye.png",
  // Africa
  "Algeria":                    T+"dz.png",
  "Angola":                     T+"ao.png",
  "Benin":                      T+"bj.png",
  "Botswana":                   T+"bw.png",
  "Burkina Faso":               T+"bf.png",
  "Burundi":                    T+"bi.png",
  "Cameroon":                   T+"cm.png",
  "Cape Verde":                 T+"cv.png",
  "Central African Republic":   T+"cf.png",
  "Chad":                       T+"td.png",
  "Comoros":                    T+"km.png",
  "Congo":                      T+"cg.png",
  "DR Congo":                   T+"cd.png",
  "Djibouti":                   T+"dj.png",
  "Egypt":                      T+"eg.png",
  "Equatorial Guinea":          T+"gq.png",
  "Eritrea":                    T+"er.png",
  "Eswatini":                   T+"sz.png",
  "Ethiopia":                   T+"et.png",
  "Gabon":                      T+"ga.png",
  "Gambia":                     T+"gm.png",
  "Ghana":                      T+"gh.png",
  "Guinea":                     T+"gn.png",
  "Guinea-Bissau":              T+"gw.png",
  "Ivory Coast":                T+"ci.png",
  "Kenya":                      T+"ke.png",
  "Lesotho":                    T+"ls.png",
  "Liberia":                    T+"lr.png",
  "Libya":                      T+"ly.png",
  "Madagascar":                 T+"mg.png",
  "Malawi":                     T+"mw.png",
  "Mali":                       T+"ml.png",
  "Mauritania":                 T+"mr.png",
  "Mauritius":                  T+"mu.png",
  "Morocco":                    T+"ma.png",
  "Mozambique":                 T+"mz.png",
  "Namibia":                    T+"na.png",
  "Niger":                      T+"ne.png",
  "Nigeria":                    T+"ng.png",
  "Rwanda":                     T+"rw.png",
  "São Tomé and Príncipe":      T+"st.png",
  "Senegal":                    T+"sn.png",
  "Seychelles":                 T+"sc.png",
  "Sierra Leone":               T+"sl.png",
  "Somalia":                    T+"so.png",
  "South Africa":               T+"za.png",
  "South Sudan":                T+"ss.png",
  "Sudan":                      T+"sd.png",
  "Tanzania":                   T+"tz.png",
  "Togo":                       T+"tg.png",
  "Tunisia":                    T+"tn.png",
  "Uganda":                     T+"ug.png",
  "Zambia":                     T+"zm.png",
  "Zimbabwe":                   T+"zw.png",
  // Oceania
  "Australia":                  T+"au.png",
  "Fiji":                       T+"fj.png",
  "Kiribati":                   T+"ki.png",
  "Marshall Islands":           T+"mh.png",
  "Micronesia":                 T+"fm.png",
  "Nauru":                      T+"nr.png",
  "New Zealand":                T+"nz.png",
  "Palau":                      T+"pw.png",
  "Papua New Guinea":           T+"pg.png",
  "Samoa":                      T+"ws.png",
  "Solomon Islands":            T+"sb.png",
  "Tonga":                      T+"to.png",
  "Tuvalu":                     T+"tv.png",
  "Vanuatu":                    T+"vu.png",
};
