// icon: Simple Icons slug (https://simpleicons.org) — crisp vector SVG
// color: brand hex color for the icon fill
// domain: fallback for brands not in Simple Icons (Google favicon)
const LOGO_DATA = {
  // Tech
  "Apple":            { icon: "apple",           color: "000000" },
  "Google":           { icon: "google",          color: "4285F4" },
  "Microsoft":        { icon: "microsoft",       color: "0078D4" },
  "Amazon":           { icon: "amazon",          color: "FF9900" },
  "Meta":             { icon: "meta",            color: "0082FB" },
  "Netflix":          { icon: "netflix",         color: "E50914" },
  "Tesla":            { icon: "tesla",           color: "CC0000" },
  "Samsung":          { icon: "samsung",         color: "1428A0" },
  "Nvidia":           { icon: "nvidia",          color: "76B900" },
  "Adobe":            { icon: "adobe",           color: "FF0000" },
  "Spotify":          { icon: "spotify",         color: "1DB954" },
  "Uber":             { icon: "uber",            color: "000000" },
  "Airbnb":           { icon: "airbnb",          color: "FF5A5F" },
  "X (Twitter)":      { icon: "x",               color: "000000" },
  "LinkedIn":         { icon: "linkedin",        color: "0A66C2" },
  "Zoom":             { icon: "zoom",            color: "0B5CFF" },
  "Slack":            { icon: "slack",           color: "4A154B" },
  "Dropbox":          { icon: "dropbox",         color: "0061FF" },
  "Snapchat":         { icon: "snapchat",        color: "FFFC00" },
  "TikTok":           { icon: "tiktok",          color: "000000" },
  "YouTube":          { icon: "youtube",         color: "FF0000" },
  "GitHub":           { icon: "github",          color: "181717" },
  "PayPal":           { icon: "paypal",          color: "003087" },
  "Shopify":          { icon: "shopify",         color: "7AB55C" },
  "Discord":          { icon: "discord",         color: "5865F2" },
  "Intel":            { icon: "intel",           color: "0071C5" },
  "Oracle":           { icon: "oracle",          color: "F80000" },
  "IBM":              { icon: "ibm",             color: "052FAD" },
  // Food & Beverage
  "McDonald's":       { icon: "mcdonalds",       color: "FFC72C" },
  "Starbucks":        { icon: "starbucks",       color: "00704A" },
  "Coca-Cola":        { icon: "cocacola",        color: "F40009" },
  "Pepsi":            { icon: "pepsi",           color: "004B93" },
  "KFC":              { icon: "kfc",             color: "F40027" },
  "Burger King":      { icon: "burgerking",      color: "D62300" },
  "Subway":           { icon: "subway",          color: "009B3A" },
  "Pizza Hut":        { icon: "pizzahut",        color: "EE3124" },
  "Domino's":         { icon: "dominospizza",    color: "006491" },
  "Dunkin":           { icon: "dunkin",          color: "FF671F" },
  "Chipotle":         { icon: "chipotle",        color: "A81612" },
  "Wendy's":          { icon: "wendys",          color: "E2203D" },
  "Taco Bell":        { icon: "tacobell",        color: "702082" },
  "Red Bull":         { icon: "redbull",         color: "CC1B28" },
  "Nestle":           { icon: "nestle",          color: "009FDA" },
  // Sports
  "Nike":             { icon: "nike",            color: "000000" },
  "Adidas":           { icon: "adidas",          color: "000000" },
  "Puma":             { icon: "puma",            color: "000000" },
  "Under Armour":     { icon: "underarmour",     color: "1D1D1B" },
  "New Balance":      { icon: "newbalance",      color: "CF0A2C" },
  "Reebok":           { icon: "reebok",          color: "000000" },
  "ESPN":             { icon: "espn",            color: "CC0000" },
  "NBA":              { icon: "nba",             color: "006BB6" },
  "NFL":              { icon: "nfl",             color: "013369" },
  // Automotive
  "Toyota":           { icon: "toyota",          color: "EB0A1E" },
  "BMW":              { icon: "bmw",             color: "0066B1" },
  "Mercedes-Benz":    { icon: "mercedesbenz",    color: "222222" },
  "Ford":             { icon: "ford",            color: "003F7F" },
  "Honda":            { icon: "honda",           color: "CC0000" },
  "Volkswagen":       { icon: "volkswagen",      color: "001E50" },
  "Ferrari":          { icon: "ferrari",         color: "DC0000" },
  "Lamborghini":      { icon: "lamborghini",     color: "CC9900" },
  "Porsche":          { icon: "porsche",         color: "D5001C" },
  "Audi":             { icon: "audi",            color: "000000" },
  // Fashion (Simple Icons has limited fashion coverage — domain fallback used)
  "Louis Vuitton":    { domain: "louisvuitton.com" },
  "Gucci":            { domain: "gucci.com" },
  "Chanel":           { domain: "chanel.com" },
  "Prada":            { domain: "prada.com" },
  "H&M":              { icon: "hm",              color: "E50010" },
  "Zara":             { domain: "zara.com" },
  "Ralph Lauren":     { domain: "ralphlauren.com" },
  "Versace":          { domain: "versace.com" },
  "Burberry":         { domain: "burberry.com" },
  // Entertainment
  "Disney":           { icon: "disney",          color: "113CCF" },
  "Warner Bros":      { domain: "warnerbros.com" },
  "Universal":        { domain: "universalstudios.com" },
  "Sony":             { icon: "sony",            color: "003087" },
  "Marvel":           { domain: "marvel.com" },
  "HBO":              { icon: "hbo",             color: "000000" },
  "Nintendo":         { icon: "nintendo",        color: "E60012" },
  "PlayStation":      { icon: "playstation",     color: "003087" },
  "Xbox":             { icon: "xbox",            color: "107C10" },
  "EA":               { icon: "ea",              color: "000000" },
  "Steam":            { icon: "steam",           color: "000000" },
  "Rockstar Games":   { icon: "rockstargames",   color: "FCAF17" },
  // Social
  "Instagram":        { icon: "instagram",       color: "E4405F" },
  "Facebook":         { icon: "facebook",        color: "1877F2" },
  "Reddit":           { icon: "reddit",          color: "FF4500" },
  "Pinterest":        { icon: "pinterest",       color: "E60023" },
  "WhatsApp":         { icon: "whatsapp",        color: "25D366" },
  "Twitch":           { icon: "twitch",          color: "9146FF" },
  // Finance
  "Visa":             { icon: "visa",            color: "1A1F71" },
  "Mastercard":       { icon: "mastercard",      color: "EB001B" },
  "American Express": { icon: "americanexpress", color: "007BC1" },
  "Stripe":           { icon: "stripe",          color: "008CDD" },
  // Retail
  "Walmart":          { icon: "walmart",         color: "0071CE" },
  "Target":           { icon: "target",          color: "CC0000" },
  "IKEA":             { icon: "ikea",            color: "0058A3" },
  "eBay":             { icon: "ebay",            color: "E53238" },
  "Costco":           { domain: "costco.com" },
  "Home Depot":       { icon: "homedepot",       color: "F96302" },
  "Best Buy":         { icon: "bestbuy",         color: "0046BE" },
};
