const LOGO_DOMAINS = {
  // Tech
  "Apple":           "apple.com",
  "Google":          "google.com",
  "Microsoft":       "microsoft.com",
  "Amazon":          "amazon.com",
  "Meta":            "meta.com",
  "Netflix":         "netflix.com",
  "Tesla":           "tesla.com",
  "Samsung":         "samsung.com",
  "Nvidia":          "nvidia.com",
  "Adobe":           "adobe.com",
  "Spotify":         "spotify.com",
  "Uber":            "uber.com",
  "Airbnb":          "airbnb.com",
  "X (Twitter)":     "x.com",
  "LinkedIn":        "linkedin.com",
  "Zoom":            "zoom.us",
  "Slack":           "slack.com",
  "Dropbox":         "dropbox.com",
  "Snapchat":        "snapchat.com",
  "TikTok":          "tiktok.com",
  "YouTube":         "youtube.com",
  "GitHub":          "github.com",
  "PayPal":          "paypal.com",
  "Shopify":         "shopify.com",
  "Discord":         "discord.com",
  "Intel":           "intel.com",
  "Oracle":          "oracle.com",
  "IBM":             "ibm.com",

  // Food & Beverage
  "McDonald's":      "mcdonalds.com",
  "Starbucks":       "starbucks.com",
  "Coca-Cola":       "coca-cola.com",
  "Pepsi":           "pepsi.com",
  "KFC":             "kfc.com",
  "Burger King":     "burgerking.com",
  "Subway":          "subway.com",
  "Pizza Hut":       "pizzahut.com",
  "Domino's":        "dominos.com",
  "Dunkin":          "dunkindonuts.com",
  "Chipotle":        "chipotle.com",
  "Wendy's":         "wendys.com",
  "Taco Bell":       "tacobell.com",
  "Red Bull":        "redbull.com",
  "Nestle":          "nestle.com",

  // Sports
  "Nike":            "nike.com",
  "Adidas":          "adidas.com",
  "Puma":            "puma.com",
  "Under Armour":    "underarmour.com",
  "New Balance":     "newbalance.com",
  "Reebok":          "reebok.com",
  "ESPN":            "espn.com",
  "NBA":             "nba.com",
  "NFL":             "nfl.com",

  // Automotive
  "Toyota":          "toyota.com",
  "BMW":             "bmw.com",
  "Mercedes-Benz":   "mercedes-benz.com",
  "Ford":            "ford.com",
  "Honda":           "honda.com",
  "Volkswagen":      "volkswagen.com",
  "Ferrari":         "ferrari.com",
  "Lamborghini":     "lamborghini.com",
  "Porsche":         "porsche.com",
  "Audi":            "audi.com",

  // Fashion
  "Louis Vuitton":   "louisvuitton.com",
  "Gucci":           "gucci.com",
  "Chanel":          "chanel.com",
  "Prada":           "prada.com",
  "H&M":             "hm.com",
  "Zara":            "zara.com",
  "Ralph Lauren":    "ralphlauren.com",
  "Versace":         "versace.com",
  "Burberry":        "burberry.com",

  // Entertainment
  "Disney":          "disney.com",
  "Warner Bros":     "warnerbros.com",
  "Universal":       "universalstudios.com",
  "Sony":            "sony.com",
  "Marvel":          "marvel.com",
  "HBO":             "hbo.com",
  "Nintendo":        "nintendo.com",
  "PlayStation":     "playstation.com",
  "Xbox":            "xbox.com",
  "EA":              "ea.com",
  "Steam":           "steampowered.com",
  "Rockstar Games":  "rockstargames.com",

  // Social
  "Instagram":       "instagram.com",
  "Facebook":        "facebook.com",
  "Reddit":          "reddit.com",
  "Pinterest":       "pinterest.com",
  "WhatsApp":        "whatsapp.com",
  "Twitch":          "twitch.tv",

  // Finance
  "Visa":            "visa.com",
  "Mastercard":      "mastercard.com",
  "American Express":"americanexpress.com",
  "Stripe":          "stripe.com",

  // Retail
  "Walmart":         "walmart.com",
  "Target":          "target.com",
  "IKEA":            "ikea.com",
  "eBay":            "ebay.com",
  "Costco":          "costco.com",
  "Home Depot":      "homedepot.com",
  "Best Buy":        "bestbuy.com",
};
