// icon:   Simple Icons slug — confirmed present in Simple Icons dataset
// color:  brand hex color for the icon fill
// url:    Wikimedia SVG thumbnail — used when no Simple Icons entry exists
// domain: last-resort Google favicon fallback
const LOGO_DATA = {
  // ── Tech ──────────────────────────────────────────────────────────────────
  "Apple":            { icon: "apple",       color: "000000", domain: "apple.com" },
  "Google":           { icon: "google",      color: "4285F4", domain: "google.com" },
  "Microsoft":        { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/330px-Microsoft_logo_%282012%29.svg.png", domain: "microsoft.com" },
  "Amazon":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/330px-Amazon_logo.svg.png", domain: "amazon.com" },
  "Meta":             { icon: "meta",        color: "0082FB", domain: "meta.com" },
  "Netflix":          { icon: "netflix",     color: "E50914", domain: "netflix.com" },
  "Tesla":            { icon: "tesla",       color: "CC0000", domain: "tesla.com" },
  "Samsung":          { icon: "samsung",     color: "1428A0", domain: "samsung.com" },
  "Nvidia":           { icon: "nvidia",      color: "76B900", domain: "nvidia.com" },
  "Adobe":            { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Adobe_logo_and_wordmark_%282017%29.svg/330px-Adobe_logo_and_wordmark_%282017%29.svg.png", domain: "adobe.com" },
  "Spotify":          { icon: "spotify",     color: "1DB954", domain: "spotify.com" },
  "Uber":             { icon: "uber",        color: "000000", domain: "uber.com" },
  "Airbnb":           { icon: "airbnb",      color: "FF5A5F", domain: "airbnb.com" },
  "X (Twitter)":      { icon: "x",           color: "000000", domain: "x.com" },
  "LinkedIn":         { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/LinkedIn_Logo_2013.svg/330px-LinkedIn_Logo_2013.svg.png", domain: "linkedin.com" },
  "Zoom":             { icon: "zoom",        color: "0B5CFF", domain: "zoom.us" },
  "Slack":            { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Slack_Technologies_Logo.svg/330px-Slack_Technologies_Logo.svg.png", domain: "slack.com" },
  "Dropbox":          { icon: "dropbox",     color: "0061FF", domain: "dropbox.com" },
  "Snapchat":         { icon: "snapchat",    color: "FFFC00", domain: "snapchat.com" },
  "TikTok":           { icon: "tiktok",      color: "000000", domain: "tiktok.com" },
  "YouTube":          { icon: "youtube",     color: "FF0000", domain: "youtube.com" },
  "GitHub":           { icon: "github",      color: "181717", domain: "github.com" },
  "PayPal":           { icon: "paypal",      color: "003087", domain: "paypal.com" },
  "Shopify":          { icon: "shopify",     color: "7AB55C", domain: "shopify.com" },
  "Discord":          { icon: "discord",     color: "5865F2", domain: "discord.com" },
  "Intel":            { icon: "intel",       color: "0071C5", domain: "intel.com" },
  "Oracle":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Oracle_logo.svg/330px-Oracle_logo.svg.png", domain: "oracle.com" },
  "IBM":              { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/IBM_logo.svg/330px-IBM_logo.svg.png", domain: "ibm.com" },
  // ── Food & Beverage ───────────────────────────────────────────────────────
  "McDonald's":       { icon: "mcdonalds",   color: "FFC72C", domain: "mcdonalds.com" },
  "Starbucks":        { icon: "starbucks",   color: "00704A", domain: "starbucks.com" },
  "Coca-Cola":        { icon: "cocacola",    color: "F40009", domain: "coca-cola.com" },
  "Pepsi":            { icon: "pepsi",       color: "004B93", domain: "pepsi.com" },
  "KFC":              { icon: "kfc",         color: "F40027", domain: "kfc.com" },
  "Burger King":      { icon: "burgerking",  color: "D62300", domain: "burgerking.com" },
  "Subway":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Subway_2016_logo.svg/330px-Subway_2016_logo.svg.png", domain: "subway.com" },
  "Pizza Hut":        { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Pizza_Hut_2025.svg/330px-Pizza_Hut_2025.svg.png", domain: "pizzahut.com" },
  "Domino's":         { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Domino%27s_pizza_logo.svg/300px-Domino%27s_pizza_logo.svg.png", domain: "dominos.com" },
  "Dunkin":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Dunkin%27_logo.svg/300px-Dunkin%27_logo.svg.png", domain: "dunkindonuts.com" },
  "Chipotle":         { domain: "chipotle.com" },
  "Wendy's":          { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Wendy%27s_logo_2012.svg/300px-Wendy%27s_logo_2012.svg.png", domain: "wendys.com" },
  "Taco Bell":        { icon: "tacobell",    color: "702082", domain: "tacobell.com" },
  "Red Bull":         { icon: "redbull",     color: "DB0A40", domain: "redbull.com" },
  "Nestle":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Nestl%C3%A9_textlogo.svg/300px-Nestl%C3%A9_textlogo.svg.png", domain: "nestle.com" },
  // ── Sports ────────────────────────────────────────────────────────────────
  "Nike":             { icon: "nike",        color: "000000", domain: "nike.com" },
  "Adidas":           { icon: "adidas",      color: "000000", domain: "adidas.com" },
  "Puma":             { icon: "puma",        color: "000000", domain: "puma.com" },
  "Under Armour":     { icon: "underarmour", color: "1D1D1D", domain: "underarmour.com" },
  "New Balance":      { icon: "newbalance",  color: "CF0A2C", domain: "newbalance.com" },
  "Reebok":           { icon: "reebok",      color: "E41D1B", domain: "reebok.com" },
  "ESPN":             { icon: "espn",        color: "CC0000", domain: "espn.com" },
  "NBA":              { icon: "nba",         color: "006BB6", domain: "nba.com" },
  "NFL":              { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/NFL_wordmark_logo_2008.svg/300px-NFL_wordmark_logo_2008.svg.png", domain: "nfl.com" },
  // ── Automotive ────────────────────────────────────────────────────────────
  "Toyota":           { icon: "toyota",      color: "EB0A1E", domain: "toyota.com" },
  "BMW":              { icon: "bmw",         color: "0066B1", domain: "bmw.com" },
  "Mercedes-Benz":    { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Mercedes-Benz_Logo_2010.svg/330px-Mercedes-Benz_Logo_2010.svg.png", domain: "mercedes-benz.com" },
  "Ford":             { icon: "ford",        color: "003F7F", domain: "ford.com" },
  "Honda":            { icon: "honda",       color: "CC0000", domain: "honda.com" },
  "Volkswagen":       { icon: "volkswagen",  color: "001E50", domain: "volkswagen.com" },
  "Ferrari":          { icon: "ferrari",     color: "DC0000", domain: "ferrari.com" },
  "Lamborghini":      { icon: "lamborghini", color: "CC9900", domain: "lamborghini.com" },
  "Porsche":          { icon: "porsche",     color: "D5001C", domain: "porsche.com" },
  "Audi":             { icon: "audi",        color: "000000", domain: "audi.com" },
  // ── Fashion ───────────────────────────────────────────────────────────────
  "Louis Vuitton":    { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Louis_Vuitton_logo_and_wordmark.svg/300px-Louis_Vuitton_logo_and_wordmark.svg.png", domain: "louisvuitton.com" },
  "Gucci":            { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Gucci_logo.svg/300px-Gucci_logo.svg.png", domain: "gucci.com" },
  "Chanel":           { url: "https://upload.wikimedia.org/wikipedia/en/thumb/9/92/Chanel_logo_interlocking_cs.svg/300px-Chanel_logo_interlocking_cs.svg.png", domain: "chanel.com" },
  "Prada":            { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Prada-Logo.svg/300px-Prada-Logo.svg.png", domain: "prada.com" },
  "H&M":              { icon: "hm",          color: "E50010", domain: "hm.com" },
  "Zara":             { icon: "zara",        color: "000000", domain: "zara.com" },
  "Ralph Lauren":     { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Ralph_Lauren_logo.svg/300px-Ralph_Lauren_logo.svg.png", domain: "ralphlauren.com" },
  "Versace":          { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Versace_old_logo.svg/300px-Versace_old_logo.svg.png", domain: "versace.com" },
  "Burberry":         { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Logo_Burberry_01.svg/300px-Logo_Burberry_01.svg.png", domain: "burberry.com" },
  // ── Entertainment ─────────────────────────────────────────────────────────
  "Disney":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Walt_Disney_wordmark.svg/330px-Walt_Disney_wordmark.svg.png", domain: "disney.com" },
  "Warner Bros":      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Warner_Bros._Discovery_%28symbol%29.svg/300px-Warner_Bros._Discovery_%28symbol%29.svg.png", domain: "warnerbros.com" },
  "Universal":        { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Universal_Pictures_logo.svg/300px-Universal_Pictures_logo.svg.png", domain: "universalpictures.com" },
  "Sony":             { icon: "sony",        color: "003087", domain: "sony.com" },
  "Marvel":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Marvel_Comics_2024_logo.svg/300px-Marvel_Comics_2024_logo.svg.png", domain: "marvel.com" },
  "HBO":              { icon: "hbo",         color: "000000", domain: "hbo.com" },
  "Nintendo":         { icon: "nintendo",    color: "E60012", domain: "nintendo.com" },
  "PlayStation":      { icon: "playstation", color: "003087", domain: "playstation.com" },
  "Xbox":             { icon: "xbox",        color: "107C10", domain: "xbox.com" },
  "EA":               { icon: "ea",          color: "000000", domain: "ea.com" },
  "Steam":            { icon: "steam",       color: "000000", domain: "store.steampowered.com" },
  "Rockstar Games":   { icon: "rockstargames", color: "FCAF17", domain: "rockstargames.com" },
  // ── Social ────────────────────────────────────────────────────────────────
  "Instagram":        { icon: "instagram",   color: "E4405F", domain: "instagram.com" },
  "Facebook":         { icon: "facebook",    color: "1877F2", domain: "facebook.com" },
  "Reddit":           { icon: "reddit",      color: "FF4500", domain: "reddit.com" },
  "Pinterest":        { icon: "pinterest",   color: "E60023", domain: "pinterest.com" },
  "WhatsApp":         { icon: "whatsapp",    color: "25D366", domain: "whatsapp.com" },
  "Twitch":           { icon: "twitch",      color: "9146FF", domain: "twitch.tv" },
  // ── Finance ───────────────────────────────────────────────────────────────
  "Visa":             { icon: "visa",        color: "1A1F71", domain: "visa.com" },
  "Mastercard":       { icon: "mastercard",  color: "EB001B", domain: "mastercard.com" },
  "American Express": { icon: "americanexpress", color: "007BC1", domain: "americanexpress.com" },
  "Stripe":           { icon: "stripe",      color: "008CDD", domain: "stripe.com" },
  // ── Retail ────────────────────────────────────────────────────────────────
  "Walmart":          { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Walmart_logo_%282008%29.svg/330px-Walmart_logo_%282008%29.svg.png", domain: "walmart.com" },
  "Target":           { icon: "target",      color: "CC0000", domain: "target.com" },
  "IKEA":             { icon: "ikea",        color: "0058A3", domain: "ikea.com" },
  "eBay":             { icon: "ebay",        color: "E53238", domain: "ebay.com" },
  "Costco":           { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Costco_Wholesale_logo_2010-10-26.svg/300px-Costco_Wholesale_logo_2010-10-26.svg.png", domain: "costco.com" },
  "Home Depot":       { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/TheHomeDepot.svg/300px-TheHomeDepot.svg.png", domain: "homedepot.com" },
  "Best Buy":         { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Best_Buy_logo_2018.svg/300px-Best_Buy_logo_2018.svg.png", domain: "bestbuy.com" },
};
