const IMAGE_URLS = {
  // Hostile Mobs
  "Creeper":               "https://minecraft.wiki/images/thumb/Creeper_JE3_BE1.png/300px-Creeper_JE3_BE1.png",
  "Zombie":                "https://minecraft.wiki/images/thumb/Zombie_JE3_BE2.png/300px-Zombie_JE3_BE2.png",
  "Skeleton":              "https://minecraft.wiki/images/thumb/Lefthandedskeleton.png/300px-Lefthandedskeleton.png",
  "Spider":                "https://minecraft.wiki/images/thumb/Spider_JE5_BE4.png/300px-Spider_JE5_BE4.png",
  "Enderman":              "https://minecraft.wiki/images/thumb/Enderman_JE3_BE1.png/300px-Enderman_JE3_BE1.png",
  "Witch":                 "https://minecraft.wiki/images/thumb/Witch_JE3.png/300px-Witch_JE3.png",
  "Blaze":                 "https://minecraft.wiki/images/Blaze_JE2.gif",
  "Ghast":                 "https://minecraft.wiki/images/thumb/Ghast_JE3_BE3.gif/300px-Ghast_JE3_BE3.gif",
  "Slime":                 "https://minecraft.wiki/images/thumb/Slime_JE3_BE2.png/300px-Slime_JE3_BE2.png",
  "Cave Spider":           "https://minecraft.wiki/images/thumb/Cave_Spider_JE3_BE3.png/300px-Cave_Spider_JE3_BE3.png",
  "Wither Skeleton":       "https://minecraft.wiki/images/thumb/Wither_Skeleton_JE4_BE3.png/300px-Wither_Skeleton_JE4_BE3.png",
  "Pillager":              "https://minecraft.wiki/images/thumb/Pillager_JE3.png/300px-Pillager_JE3.png",
  "Phantom":               "https://minecraft.wiki/images/Phantom_JE2.gif",
  "Guardian":              "https://minecraft.wiki/images/Guardian_JE2_BE2.gif",
  "Elder Guardian":        "https://minecraft.wiki/images/Elder_Guardian_JE2_BE2.gif",
  "Warden":                "https://minecraft.wiki/images/Warden.gif",
  "Husk":                  "https://minecraft.wiki/images/thumb/Husk_JE2_BE2.png/300px-Husk_JE2_BE2.png",
  "Drowned":               "https://minecraft.wiki/images/thumb/Drowned_JE1.png/300px-Drowned_JE1.png",
  "Magma Cube":            "https://minecraft.wiki/images/thumb/Magma_Cube_JE2_BE2.png/300px-Magma_Cube_JE2_BE2.png",
  "Endermite":             "https://minecraft.wiki/images/Endermite.gif",
  "Silverfish":            "https://minecraft.wiki/images/thumb/Silverfish_JE1_BE1.gif/300px-Silverfish_JE1_BE1.gif",
  "Ravager":               "https://minecraft.wiki/images/thumb/Ravager_JE1.png/300px-Ravager_JE1.png",
  "Evoker":                "https://minecraft.wiki/images/thumb/Evoker_Summoning_Vexes.png/300px-Evoker_Summoning_Vexes.png",
  "Vex":                   "https://minecraft.wiki/images/thumb/Vex_JE4.gif/300px-Vex_JE4.gif",
  "Vindicator":            "https://minecraft.wiki/images/thumb/Vindicator_attacking.png/300px-Vindicator_attacking.png",
  "Hoglin":                "https://minecraft.wiki/images/thumb/Hoglin_JE3.png/300px-Hoglin_JE3.png",
  "Zoglin":                "https://minecraft.wiki/images/thumb/Zoglin_JE1.png/300px-Zoglin_JE1.png",
  "Stray":                 "https://minecraft.wiki/images/thumb/Stray_JE2_BE4.png/300px-Stray_JE2_BE4.png",
  "Bogged":                "https://minecraft.wiki/images/thumb/Bogged_JE2_BE2.png/300px-Bogged_JE2_BE2.png",
  "Breeze":                "https://minecraft.wiki/images/Breeze_JE1.webp",
  "Shulker":               "https://minecraft.wiki/images/Shulker_JE1_BE1.png",
  "Zombie Villager":       "https://minecraft.wiki/images/thumb/Plains_Zombie_Villager_Base_JE1_BE1.png/300px-Plains_Zombie_Villager_Base_JE1_BE1.png",
  "Piglin Brute":          "https://minecraft.wiki/images/thumb/Piglin_Brute_JE1_BE1.png/300px-Piglin_Brute_JE1_BE1.png",
  "Creaking":              "https://minecraft.wiki/images/Creaking_JE1_BE1.png",
  // Passive / Neutral Mobs
  "Steve":                 "https://minecraft.wiki/images/thumb/Steve_%28classic%29_JE6.png/300px-Steve_%28classic%29_JE6.png",
  "Alex":                  "https://minecraft.wiki/images/thumb/Alex_%28slim%29_JE3.png/300px-Alex_%28slim%29_JE3.png",
  "Cow":                   "https://minecraft.wiki/images/thumb/Cow_JE7_BE4.png/300px-Cow_JE7_BE4.png",
  "Pig":                   "https://minecraft.wiki/images/thumb/Temperate_Pig_JE4_BE2.png/300px-Temperate_Pig_JE4_BE2.png",
  "Chicken":               "https://minecraft.wiki/images/thumb/Chicken_JE2_BE2.png/300px-Chicken_JE2_BE2.png",
  "Sheep":                 "https://minecraft.wiki/images/thumb/White_Sheep_JE4_BE7.png/300px-White_Sheep_JE4_BE7.png",
  "Horse":                 "https://minecraft.wiki/images/thumb/White_Horse.png/300px-White_Horse.png",
  "Donkey":                "https://minecraft.wiki/images/thumb/Donkey_JE5.png/300px-Donkey_JE5.png",
  "Mule":                  "https://minecraft.wiki/images/thumb/Mule_JE5.png/300px-Mule_JE5.png",
  "Skeleton Horse":        "https://minecraft.wiki/images/thumb/Skeleton_Horse.png/300px-Skeleton_Horse.png",
  "Zombie Horse":          "https://minecraft.wiki/images/thumb/Zombie_Horse_JE6.png/300px-Zombie_Horse_JE6.png",
  "Villager":              "https://minecraft.wiki/images/thumb/Plains_Villager_Base_JE2.png/300px-Plains_Villager_Base_JE2.png",
  "Wandering Trader":      "https://minecraft.wiki/images/thumb/Wandering_Trader_JE1_BE1.png/300px-Wandering_Trader_JE1_BE1.png",
  "Wolf":                  "https://minecraft.wiki/images/thumb/Wolf_JE2_BE2.png/300px-Wolf_JE2_BE2.png",
  "Cat":                   "https://minecraft.wiki/images/thumb/Tabby_Cat.png/300px-Tabby_Cat.png",
  "Ocelot":                "https://minecraft.wiki/images/thumb/Ocelot_JE2_BE2.png/300px-Ocelot_JE2_BE2.png",
  "Rabbit":                "https://minecraft.wiki/images/thumb/Brown_Rabbit_BE4.png/300px-Brown_Rabbit_BE4.png",
  "Bee":                   "https://minecraft.wiki/images/thumb/Baby_Bee_JE2.gif/300px-Baby_Bee_JE2.gif",
  "Fox":                   "https://minecraft.wiki/images/thumb/Fox_JE1_BE1.png/300px-Fox_JE1_BE1.png",
  "Axolotl":               "https://minecraft.wiki/images/thumb/Axolotl_Idle_Floor_Underwater.gif/300px-Axolotl_Idle_Floor_Underwater.gif",
  "Iron Golem":            "https://minecraft.wiki/images/thumb/Iron_Golem_JE2_BE2.png/300px-Iron_Golem_JE2_BE2.png",
  "Snow Golem":            "https://minecraft.wiki/images/thumb/Snow_Golem_JE2_BE2.png/300px-Snow_Golem_JE2_BE2.png",
  "Mooshroom":             "https://minecraft.wiki/images/thumb/Red_Mooshroom_JE5_BE3.png/300px-Red_Mooshroom_JE5_BE3.png",
  "Panda":                 "https://minecraft.wiki/images/thumb/Panda_JE1_BE1.png/300px-Panda_JE1_BE1.png",
  "Turtle":                "https://minecraft.wiki/images/thumb/Turtle_JE3_BE1.png/300px-Turtle_JE3_BE1.png",
  "Dolphin":               "https://minecraft.wiki/images/thumb/Dolphin.gif/300px-Dolphin.gif",
  "Parrot":                "https://minecraft.wiki/images/thumb/Red_Parrot_JE1_BE1.png/300px-Red_Parrot_JE1_BE1.png",
  "Llama":                 "https://minecraft.wiki/images/thumb/Brown_Llama_JE2_BE2.png/300px-Brown_Llama_JE2_BE2.png",
  "Trader Llama":          "https://minecraft.wiki/images/thumb/Brown_Trader_Llama.png/300px-Brown_Trader_Llama.png",
  "Squid":                 "https://minecraft.wiki/images/Squid_JE2_BE2.gif",
  "Glow Squid":            "https://minecraft.wiki/images/Glow_Squid_JE1.gif",
  "Bat":                   "https://minecraft.wiki/images/Bat_JE4_BE3.gif",
  "Allay":                 "https://minecraft.wiki/images/Allay_JE2_BE2.gif",
  "Camel":                 "https://minecraft.wiki/images/thumb/Camel_Idle.gif/300px-Camel_Idle.gif",
  "Frog":                  "https://minecraft.wiki/images/Temperate_Frog_JE1_BE1.gif",
  "Tadpole":               "https://minecraft.wiki/images/thumb/Tadpole_JE1.png/300px-Tadpole_JE1.png",
  "Sniffer":               "https://minecraft.wiki/images/thumb/Sniffer_sniffsniff.gif/300px-Sniffer_sniffsniff.gif",
  "Strider":               "https://minecraft.wiki/images/Strider_JE2_BE2.gif",
  "Goat":                  "https://minecraft.wiki/images/thumb/Goat_%28two_horns%29_JE1_BE1.png/300px-Goat_%28two_horns%29_JE1_BE1.png",
  "Polar Bear":            "https://minecraft.wiki/images/thumb/Polar_Bear_JE2_BE2.png/300px-Polar_Bear_JE2_BE2.png",
  "Piglin":                "https://minecraft.wiki/images/thumb/Piglin_JE1.png/300px-Piglin_JE1.png",
  "Zombified Piglin":      "https://minecraft.wiki/images/thumb/Zombified_Piglin_BE6.png/300px-Zombified_Piglin_BE6.png",
  "Armadillo":             "https://minecraft.wiki/images/thumb/Armadillo_JE2_BE2.png/300px-Armadillo_JE2_BE2.png",
  "Cod":                   "https://minecraft.wiki/images/Cod.gif",
  "Salmon":                "https://minecraft.wiki/images/Salmon.gif",
  "Pufferfish":            "https://minecraft.wiki/images/thumb/Pufferfish_small.gif/300px-Pufferfish_small.gif",
  "Tropical Fish":         "https://minecraft.wiki/images/thumb/Clownfish.png/300px-Clownfish.png",
  // Bosses
  "Ender Dragon":          "https://minecraft.wiki/images/thumb/Ender_Dragon.gif/300px-Ender_Dragon.gif",
  "Wither":                "https://minecraft.wiki/images/thumb/Wither_JE2_BE2.png/300px-Wither_JE2_BE2.png",
  // Blocks
  "Grass Block":           "https://minecraft.wiki/images/Grass_Block_JE7_BE6.png",
  "Dirt":                  "https://minecraft.wiki/images/Dirt_JE2_BE2.png",
  "Stone":                 "https://minecraft.wiki/images/Stone_JE5_BE3.png",
  "Cobblestone":           "https://minecraft.wiki/images/Cobblestone_JE5_BE3.png",
  "Sand":                  "https://minecraft.wiki/images/Sand_JE5_BE3.png",
  "Gravel":                "https://minecraft.wiki/images/Gravel_JE5_BE4.png",
  "Bedrock":               "https://minecraft.wiki/images/Bedrock_JE2_BE2.png",
  "TNT":                   "https://minecraft.wiki/images/TNT_JE3_BE2.png",
  "Chest":                 "https://minecraft.wiki/images/Chest.gif",
  "Trapped Chest":         "https://minecraft.wiki/images/thumb/Trapped_Chest.gif/300px-Trapped_Chest.gif",
  "Ender Chest":           "https://minecraft.wiki/images/thumb/Ender_Chest.gif/300px-Ender_Chest.gif",
  "Crafting Table":        "https://minecraft.wiki/images/Crafting_Table_JE4_BE3.png",
  "Furnace":               "https://minecraft.wiki/images/Furnace_%28S%29_JE4.png",
  "Blast Furnace":         "https://minecraft.wiki/images/thumb/Blast_Furnace_%28S%29_JE2.png/300px-Blast_Furnace_%28S%29_JE2.png",
  "Smoker":                "https://minecraft.wiki/images/thumb/Smoker_%28S%29_JE2.png/300px-Smoker_%28S%29_JE2.png",
  "Bookshelf":             "https://minecraft.wiki/images/Bookshelf_JE4_BE2.png",
  "Pumpkin":               "https://minecraft.wiki/images/Pumpkin_JE3.png",
  "Jack o'Lantern":        "https://minecraft.wiki/images/thumb/Jack_o'Lantern_JE2_BE2.png/300px-Jack_o'Lantern_JE2_BE2.png",
  "Cake":                  "https://minecraft.wiki/images/Cake_JE4.png",
  "Beacon":                "https://minecraft.wiki/images/Beacon_JE6_BE2.png",
  "Enchanting Table":      "https://minecraft.wiki/images/Enchanting_Table.gif",
  "Diamond Ore":           "https://minecraft.wiki/images/Diamond_Ore_JE5_BE5.png",
  "Emerald Ore":           "https://minecraft.wiki/images/Emerald_Ore_JE4_BE3.png",
  "Gold Ore":              "https://minecraft.wiki/images/Gold_Ore_JE7_BE4.png",
  "Iron Ore":              "https://minecraft.wiki/images/Iron_Ore_JE6_BE4.png",
  "Coal Ore":              "https://minecraft.wiki/images/Coal_Ore_JE5_BE4.png",
  "Lapis Lazuli Ore":      "https://minecraft.wiki/images/thumb/Lapis_Lazuli_Ore_JE4_BE3.png/300px-Lapis_Lazuli_Ore_JE4_BE3.png",
  "Redstone Ore":          "https://minecraft.wiki/images/thumb/Redstone_Ore_JE4_BE3.png/300px-Redstone_Ore_JE4_BE3.png",
  "Copper Ore":            "https://minecraft.wiki/images/Copper_Ore_JE2_BE2.png",
  "Ancient Debris":        "https://minecraft.wiki/images/Ancient_Debris_JE1_BE1.png",
  "Deepslate":             "https://minecraft.wiki/images/Deepslate_%28UD%29_JE3.png",
  "Obsidian":              "https://minecraft.wiki/images/Obsidian_JE3_BE2.png",
  "Crying Obsidian":       "https://minecraft.wiki/images/Crying_Obsidian_JE1_BE1.png",
  "End Portal Frame":      "https://minecraft.wiki/images/End_Portal_Frame_%28S%29_JE7.png",
  "Dragon Egg":            "https://minecraft.wiki/images/Dragon_Egg_JE5.png",
  "Glowstone":             "https://minecraft.wiki/images/Glowstone_JE4_BE2.png",
  "Soul Sand":             "https://minecraft.wiki/images/Soul_Sand_JE2_BE2.png",
  "Netherrack":            "https://minecraft.wiki/images/thumb/Netherrack_JE3_BE2.png/300px-Netherrack_JE3_BE2.png",
  "Block of Diamond":      "https://minecraft.wiki/images/Block_of_Diamond_JE5_BE3.png",
  "Block of Gold":         "https://minecraft.wiki/images/Block_of_Gold_JE6_BE3.png",
  "Block of Iron":         "https://minecraft.wiki/images/Block_of_Iron_JE4_BE3.png",
  "Block of Emerald":      "https://minecraft.wiki/images/Block_of_Emerald_JE4_BE3.png",
  "Block of Netherite":    "https://minecraft.wiki/images/Block_of_Netherite_JE1_BE1.png",
  "Hay Bale":              "https://minecraft.wiki/images/Hay_Bale_%28UD%29_JE2_BE2.png",
  "Bee Nest":              "https://minecraft.wiki/images/Bee_Nest_%28S%29_JE1.png",
  "Beehive":               "https://minecraft.wiki/images/thumb/Beehive_%28S%29_JE1.png/300px-Beehive_%28S%29_JE1.png",
  "Honey Block":           "https://minecraft.wiki/images/thumb/Honey_Block_JE1_BE1.png/300px-Honey_Block_JE1_BE1.png",
  "Honeycomb Block":       "https://minecraft.wiki/images/thumb/Honeycomb_Block_JE1_BE1.png/300px-Honeycomb_Block_JE1_BE1.png",
  "Jukebox":               "https://minecraft.wiki/images/Jukebox_JE2_BE2.png",
  "Cauldron":              "https://minecraft.wiki/images/Cauldron_JE8.png",
  "Anvil":                 "https://minecraft.wiki/images/Anvil_%28N%29_JE3.png",
  "Grindstone":            "https://minecraft.wiki/images/Grindstone_%28floor%29_%28N%29.png",
  "Bell":                  "https://minecraft.wiki/images/thumb/Bell_%28floor%29_%28S%29_JE3.png/300px-Bell_%28floor%29_%28S%29_JE3.png",
  "Lantern":               "https://minecraft.wiki/images/thumb/Lantern_%28floor%29_JE1_BE1.png/300px-Lantern_%28floor%29_JE1_BE1.png",
  "Conduit":               "https://minecraft.wiki/images/Conduit_JE1_BE1.png",
  "Lodestone":             "https://minecraft.wiki/images/Lodestone_JE1_BE1.png",
  "Respawn Anchor":        "https://minecraft.wiki/images/Respawn_Anchor_%280%29_JE1.png",
  "Amethyst Cluster":      "https://minecraft.wiki/images/thumb/Small_Amethyst_Bud_%28U%29_JE1_BE2.png/300px-Small_Amethyst_Bud_%28U%29_JE1_BE2.png",
  "Sculk":                 "https://minecraft.wiki/images/thumb/Sculk_JE1_BE1.png/300px-Sculk_JE1_BE1.png",
  "Sculk Catalyst":        "https://minecraft.wiki/images/Sculk_Catalyst_JE1.png",
  "Sculk Shrieker":        "https://minecraft.wiki/images/thumb/Sculk_Shrieker_%28can_summon%3Dfalse%29_JE2.png/300px-Sculk_Shrieker_%28can_summon%3Dfalse%29_JE2.png",
  "Moss Block":            "https://minecraft.wiki/images/Moss_Block_JE1_BE1.png",
  "Spore Blossom":         "https://minecraft.wiki/images/thumb/Spore_Blossom_JE1_BE1.png/300px-Spore_Blossom_JE1_BE1.png",
  "Composter":             "https://minecraft.wiki/images/Composter_JE1.png",
  "Target":                "https://minecraft.wiki/images/thumb/Target_JE2_BE2.png/300px-Target_JE2_BE2.png",
  "Gilded Blackstone":     "https://minecraft.wiki/images/Gilded_Blackstone_JE1_BE1.png",
  "Cartography Table":     "https://minecraft.wiki/images/thumb/Cartography_Table_JE2_BE2.png/300px-Cartography_Table_JE2_BE2.png",
  "Smithing Table":        "https://minecraft.wiki/images/thumb/Smithing_Table_JE2_BE2.png/300px-Smithing_Table_JE2_BE2.png",
  "Fletching Table":       "https://minecraft.wiki/images/thumb/Fletching_Table_JE2_BE2.png/300px-Fletching_Table_JE2_BE2.png",
  "Crafter":               "https://minecraft.wiki/images/thumb/Crafter_%28S%29_JE1.png/300px-Crafter_%28S%29_JE1.png",
  "Trial Spawner":         "https://minecraft.wiki/images/Active_Trial_Spawner_JE4_BE3.png",
  "Vault":                 "https://minecraft.wiki/images/Vault_JE6_BE5.png",
  "Creaking Heart":        "https://minecraft.wiki/images/thumb/Creaking_Heart_%28active%29_JE1_BE1.png/300px-Creaking_Heart_%28active%29_JE1_BE1.png",
  // Items
  "Diamond Sword":         "https://minecraft.wiki/images/Diamond_Sword_JE3_BE3.png",
  "Diamond Pickaxe":       "https://minecraft.wiki/images/Diamond_Pickaxe_JE3_BE3.png",
  "Diamond Axe":           "https://minecraft.wiki/images/Diamond_Axe_JE3_BE3.png",
  "Diamond Shovel":        "https://minecraft.wiki/images/thumb/Diamond_Shovel_JE3_BE3.png/300px-Diamond_Shovel_JE3_BE3.png",
  "Diamond Hoe":           "https://minecraft.wiki/images/thumb/Diamond_Hoe_JE3_BE3.png/300px-Diamond_Hoe_JE3_BE3.png",
  "Netherite Sword":       "https://minecraft.wiki/images/Netherite_Sword_JE2_BE2.png",
  "Netherite Pickaxe":     "https://minecraft.wiki/images/thumb/Netherite_Pickaxe_JE2_BE2.png/300px-Netherite_Pickaxe_JE2_BE2.png",
  "Bow":                   "https://minecraft.wiki/images/Bow_JE2_BE1.png",
  "Crossbow":              "https://minecraft.wiki/images/Crossbow.png",
  "Trident":               "https://minecraft.wiki/images/Trident.png",
  "Shield":                "https://minecraft.wiki/images/thumb/Shield_JE2_BE1.png/300px-Shield_JE2_BE1.png",
  "Arrow":                 "https://minecraft.wiki/images/Arrow_JE2_BE1.png",
  "Tipped Arrow":          "https://minecraft.wiki/images/thumb/Tipped_Arrow_JE2_BE2.png/300px-Tipped_Arrow_JE2_BE2.png",
  "Diamond Helmet":        "https://minecraft.wiki/images/thumb/Diamond_Helmet_JE2_BE2.png/300px-Diamond_Helmet_JE2_BE2.png",
  "Diamond Chestplate":    "https://minecraft.wiki/images/thumb/Diamond_Chestplate_JE3_BE2.png/300px-Diamond_Chestplate_JE3_BE2.png",
  "Diamond Leggings":      "https://minecraft.wiki/images/thumb/Diamond_Leggings_JE2_BE2.png/300px-Diamond_Leggings_JE2_BE2.png",
  "Diamond Boots":         "https://minecraft.wiki/images/Diamond_Boots_JE2_BE2.png",
  "Elytra":                "https://minecraft.wiki/images/thumb/Elytra_JE2_BE2.png/300px-Elytra_JE2_BE2.png",
  "Totem of Undying":      "https://minecraft.wiki/images/Totem_of_Undying_JE2_BE2.png",
  "Nether Star":           "https://minecraft.wiki/images/Nether_Star.gif",
  "Heart of the Sea":      "https://minecraft.wiki/images/Heart_of_the_Sea_JE1_BE2.png",
  "Ender Pearl":           "https://minecraft.wiki/images/Ender_Pearl_JE3_BE2.png",
  "Blaze Rod":             "https://minecraft.wiki/images/Blaze_Rod_JE1_BE1.png",
  "Eye of Ender":          "https://minecraft.wiki/images/Eye_of_Ender_JE2_BE2.png",
  "Diamond":               "https://minecraft.wiki/images/Diamond_JE3_BE3.png",
  "Emerald":               "https://minecraft.wiki/images/Emerald_JE3_BE3.png",
  "Coal":                  "https://minecraft.wiki/images/Coal_JE4_BE3.png",
  "Apple":                 "https://minecraft.wiki/images/Apple_JE3_BE3.png",
  "Golden Apple":          "https://minecraft.wiki/images/Golden_Apple_JE2_BE2.png",
  "Enchanted Golden Apple":"https://minecraft.wiki/images/Enchanted_Golden_Apple_JE2_BE2.gif",
  "Bread":                 "https://minecraft.wiki/images/Bread_JE3_BE3.png",
  "Cookie":                "https://minecraft.wiki/images/Cookie_JE2_BE2.png",
  "Pumpkin Pie":           "https://minecraft.wiki/images/thumb/Pumpkin_Pie_JE2_BE2.png/300px-Pumpkin_Pie_JE2_BE2.png",
  "Melon Slice":           "https://minecraft.wiki/images/thumb/Melon_Slice_JE2_BE2.png/300px-Melon_Slice_JE2_BE2.png",
  "Cooked Beef":           "https://minecraft.wiki/images/thumb/Cooked_Beef_JE3_BE3.png/300px-Cooked_Beef_JE3_BE3.png",
  "Cooked Chicken":        "https://minecraft.wiki/images/thumb/Cooked_Chicken_JE3_BE3.png/300px-Cooked_Chicken_JE3_BE3.png",
  "Golden Carrot":         "https://minecraft.wiki/images/Golden_Carrot_JE4_BE2.png",
  "Potion":                "https://minecraft.wiki/images/Water_Bottle_JE2_BE2.png",
  "Splash Potion":         "https://minecraft.wiki/images/thumb/Splash_Water_Bottle_JE2_BE2.png/300px-Splash_Water_Bottle_JE2_BE2.png",
  "Compass":               "https://minecraft.wiki/images/Compass_JE3_BE3.gif",
  "Clock":                 "https://minecraft.wiki/images/Clock_JE3_BE3.gif",
  "Map":                   "https://minecraft.wiki/images/thumb/Map_Zoom_4.png/300px-Map_Zoom_4.png",
  "Fishing Rod":           "https://minecraft.wiki/images/Fishing_Rod_JE2_BE2.png",
  "Name Tag":              "https://minecraft.wiki/images/Name_Tag_JE3_BE2.png",
  "Saddle":                "https://minecraft.wiki/images/thumb/Saddle_%28Pig%29_JE2_BE2.png/300px-Saddle_%28Pig%29_JE2_BE2.png",
  "Flint and Steel":       "https://minecraft.wiki/images/Flint_and_Steel_JE4_BE2.png",
  "Bucket":                "https://minecraft.wiki/images/Bucket_JE2_BE2.png",
  "Torch":                 "https://minecraft.wiki/images/Torch.gif",
  "Book":                  "https://minecraft.wiki/images/Book_JE2_BE2.png",
  "Enchanted Book":        "https://minecraft.wiki/images/Enchanted_Book.gif",
  "Bottle o' Enchanting":  "https://minecraft.wiki/images/thumb/Bottle_o'_Enchanting_JE2_BE1.png/300px-Bottle_o'_Enchanting_JE2_BE1.png",
  "Firework Rocket":       "https://minecraft.wiki/images/Firework_Rocket_JE2_BE2.png",
  "Wind Charge":           "https://minecraft.wiki/images/Wind_Charge_JE2_BE2.webp",
  "Mace":                  "https://minecraft.wiki/images/Mace_JE1_BE1.png",
};
