const T = "https://minecraft.wiki/w/Special:FilePath/";
const IMAGE_URLS = {
  // Hostile Mobs
  "Creeper":              T+"Creeper.png",
  "Zombie":               T+"Zombie.png",
  "Skeleton":             T+"Skeleton.png",
  "Spider":               T+"Spider.png",
  "Enderman":             T+"Enderman.png",
  "Witch":                T+"Witch.png",
  "Blaze":                T+"Blaze.png",
  "Ghast":                T+"Ghast.png",
  "Slime":                T+"Slime.png",
  "Cave Spider":          T+"Cave_Spider.png",
  "Wither Skeleton":      T+"Wither_Skeleton.png",
  "Pillager":             T+"Pillager.png",
  "Phantom":              T+"Phantom.png",
  "Guardian":             T+"Guardian.png",
  "Elder Guardian":       T+"Elder_Guardian.png",
  "Warden":               T+"Warden.png",
  "Husk":                 T+"Husk.png",
  "Drowned":              T+"Drowned.png",
  "Magma Cube":           T+"Magma_Cube.png",
  "Endermite":            T+"Endermite.png",
  "Silverfish":           T+"Silverfish.png",
  "Ravager":              T+"Ravager.png",
  "Evoker":               T+"Evoker.png",
  "Vex":                  T+"Vex.png",
  "Vindicator":           T+"Vindicator.png",
  "Hoglin":               T+"Hoglin.png",
  "Zoglin":               T+"Zoglin.png",
  "Stray":                T+"Stray.png",
  "Bogged":               T+"Bogged.png",
  "Breeze":               T+"Breeze.png",
  "Shulker":              T+"Shulker.png",
  "Zombie Villager":      T+"Zombie_Villager.png",
  "Piglin Brute":         T+"Piglin_Brute.png",
  "Creaking":             T+"Creaking.png",
  // Passive / Neutral Mobs
  "Steve":                T+"Steve.png",
  "Alex":                 T+"Alex.png",
  "Cow":                  T+"Cow.png",
  "Pig":                  T+"Pig.png",
  "Chicken":              T+"Chicken.png",
  "Sheep":                T+"Sheep.png",
  "Horse":                T+"Horse.png",
  "Donkey":               T+"Donkey.png",
  "Mule":                 T+"Mule.png",
  "Skeleton Horse":       T+"Skeleton_Horse.png",
  "Zombie Horse":         T+"Zombie_Horse.png",
  "Villager":             T+"Villager.png",
  "Wandering Trader":     T+"Wandering_Trader.png",
  "Wolf":                 T+"Wolf.png",
  "Cat":                  T+"Cat.png",
  "Ocelot":               T+"Ocelot.png",
  "Rabbit":               T+"Rabbit.png",
  "Bee":                  T+"Bee.png",
  "Fox":                  T+"Fox.png",
  "Axolotl":              T+"Axolotl.png",
  "Iron Golem":           T+"Iron_Golem.png",
  "Snow Golem":           T+"Snow_Golem.png",
  "Mooshroom":            T+"Mooshroom.png",
  "Panda":                T+"Panda.png",
  "Turtle":               T+"Turtle.png",
  "Dolphin":              T+"Dolphin.png",
  "Parrot":               T+"Parrot.png",
  "Llama":                T+"Llama.png",
  "Trader Llama":         T+"Trader_Llama.png",
  "Squid":                T+"Squid.png",
  "Glow Squid":           T+"Glow_Squid.png",
  "Bat":                  T+"Bat.png",
  "Allay":                T+"Allay.png",
  "Camel":                T+"Camel.png",
  "Frog":                 T+"Frog.png",
  "Tadpole":              T+"Tadpole.png",
  "Sniffer":              T+"Sniffer.png",
  "Strider":              T+"Strider.png",
  "Goat":                 T+"Goat.png",
  "Polar Bear":           T+"Polar_Bear.png",
  "Piglin":               T+"Piglin.png",
  "Zombified Piglin":     T+"Zombified_Piglin.png",
  "Armadillo":            T+"Armadillo.png",
  "Cod":                  T+"Cod.png",
  "Salmon":               T+"Salmon.png",
  "Pufferfish":           T+"Pufferfish.png",
  "Tropical Fish":        T+"Tropical_Fish.png",
  // Bosses
  "Ender Dragon":         T+"Ender_Dragon.png",
  "Wither":               T+"Wither.png",
  // Blocks
  "Grass Block":          T+"Grass_Block.png",
  "Dirt":                 T+"Dirt.png",
  "Stone":                T+"Stone.png",
  "Cobblestone":          T+"Cobblestone.png",
  "Sand":                 T+"Sand.png",
  "Gravel":               T+"Gravel.png",
  "Bedrock":              T+"Bedrock.png",
  "TNT":                  T+"TNT.png",
  "Chest":                T+"Chest.png",
  "Trapped Chest":        T+"Trapped_Chest.png",
  "Ender Chest":          T+"Ender_Chest.png",
  "Crafting Table":       T+"Crafting_Table.png",
  "Furnace":              T+"Furnace.png",
  "Blast Furnace":        T+"Blast_Furnace.png",
  "Smoker":               T+"Smoker.png",
  "Bookshelf":            T+"Bookshelf.png",
  "Pumpkin":              T+"Pumpkin.png",
  "Jack o'Lantern":       T+"Jack_o'Lantern.png",
  "Cake":                 T+"Cake.png",
  "Beacon":               T+"Beacon.png",
  "Enchanting Table":     T+"Enchanting_Table.png",
  "Diamond Ore":          T+"Diamond_Ore.png",
  "Emerald Ore":          T+"Emerald_Ore.png",
  "Gold Ore":             T+"Gold_Ore.png",
  "Iron Ore":             T+"Iron_Ore.png",
  "Coal Ore":             T+"Coal_Ore.png",
  "Lapis Lazuli Ore":     T+"Lapis_Lazuli_Ore.png",
  "Redstone Ore":         T+"Redstone_Ore.png",
  "Copper Ore":           T+"Copper_Ore.png",
  "Ancient Debris":       T+"Ancient_Debris.png",
  "Deepslate":            T+"Deepslate.png",
  "Obsidian":             T+"Obsidian.png",
  "Crying Obsidian":      T+"Crying_Obsidian.png",
  "End Portal Frame":     T+"End_Portal_Frame.png",
  "Dragon Egg":           T+"Dragon_Egg.png",
  "Glowstone":            T+"Glowstone.png",
  "Soul Sand":            T+"Soul_Sand.png",
  "Netherrack":           T+"Netherrack.png",
  "Block of Diamond":     T+"Block_of_Diamond.png",
  "Block of Gold":        T+"Block_of_Gold.png",
  "Block of Iron":        T+"Block_of_Iron.png",
  "Block of Emerald":     T+"Block_of_Emerald.png",
  "Block of Netherite":   T+"Block_of_Netherite.png",
  "Hay Bale":             T+"Hay_Bale.png",
  "Bee Nest":             T+"Bee_Nest.png",
  "Beehive":              T+"Beehive.png",
  "Honey Block":          T+"Honey_Block.png",
  "Honeycomb Block":      T+"Honeycomb_Block.png",
  "Jukebox":              T+"Jukebox.png",
  "Cauldron":             T+"Cauldron.png",
  "Anvil":                T+"Anvil.png",
  "Grindstone":           T+"Grindstone.png",
  "Bell":                 T+"Bell.png",
  "Lantern":              T+"Lantern.png",
  "Conduit":              T+"Conduit.png",
  "Lodestone":            T+"Lodestone.png",
  "Respawn Anchor":       T+"Respawn_Anchor.png",
  "Amethyst Cluster":     T+"Amethyst_Cluster.png",
  "Sculk":                T+"Sculk.png",
  "Sculk Catalyst":       T+"Sculk_Catalyst.png",
  "Sculk Shrieker":       T+"Sculk_Shrieker.png",
  "Moss Block":           T+"Moss_Block.png",
  "Spore Blossom":        T+"Spore_Blossom.png",
  "Composter":            T+"Composter.png",
  "Target":               T+"Target.png",
  "Gilded Blackstone":    T+"Gilded_Blackstone.png",
  "Cartography Table":    T+"Cartography_Table.png",
  "Smithing Table":       T+"Smithing_Table.png",
  "Fletching Table":      T+"Fletching_Table.png",
  "Crafter":              T+"Crafter.png",
  "Trial Spawner":        T+"Trial_Spawner.png",
  "Vault":                T+"Vault.png",
  "Creaking Heart":       T+"Creaking_Heart.png",
  // Items
  "Diamond Sword":        T+"Diamond_Sword.png",
  "Diamond Pickaxe":      T+"Diamond_Pickaxe.png",
  "Diamond Axe":          T+"Diamond_Axe.png",
  "Diamond Shovel":       T+"Diamond_Shovel.png",
  "Diamond Hoe":          T+"Diamond_Hoe.png",
  "Netherite Sword":      T+"Netherite_Sword.png",
  "Netherite Pickaxe":    T+"Netherite_Pickaxe.png",
  "Bow":                  T+"Bow.png",
  "Crossbow":             T+"Crossbow.png",
  "Trident":              T+"Trident.png",
  "Shield":               T+"Shield.png",
  "Arrow":                T+"Arrow.png",
  "Tipped Arrow":         T+"Tipped_Arrow.png",
  "Diamond Helmet":       T+"Diamond_Helmet.png",
  "Diamond Chestplate":   T+"Diamond_Chestplate.png",
  "Diamond Leggings":     T+"Diamond_Leggings.png",
  "Diamond Boots":        T+"Diamond_Boots.png",
  "Elytra":               T+"Elytra.png",
  "Totem of Undying":     T+"Totem_of_Undying.png",
  "Nether Star":          T+"Nether_Star.png",
  "Heart of the Sea":     T+"Heart_of_the_Sea.png",
  "Ender Pearl":          T+"Ender_Pearl.png",
  "Blaze Rod":            T+"Blaze_Rod.png",
  "Eye of Ender":         T+"Eye_of_Ender.png",
  "Diamond":              T+"Diamond.png",
  "Emerald":              T+"Emerald.png",
  "Coal":                 T+"Coal.png",
  "Apple":                T+"Apple.png",
  "Golden Apple":         T+"Golden_Apple.png",
  "Enchanted Golden Apple": T+"Enchanted_Golden_Apple.png",
  "Bread":                T+"Bread.png",
  "Cookie":               T+"Cookie.png",
  "Pumpkin Pie":          T+"Pumpkin_Pie.png",
  "Melon Slice":          T+"Melon_Slice.png",
  "Cooked Beef":          T+"Cooked_Beef.png",
  "Cooked Chicken":       T+"Cooked_Chicken.png",
  "Golden Carrot":        T+"Golden_Carrot.png",
  "Potion":               T+"Potion.png",
  "Splash Potion":        T+"Splash_Potion.png",
  "Compass":              T+"Compass.png",
  "Clock":                T+"Clock.png",
  "Map":                  T+"Map.png",
  "Fishing Rod":          T+"Fishing_Rod.png",
  "Lead":                 T+"Lead.png",
  "Name Tag":             T+"Name_Tag.png",
  "Saddle":               T+"Saddle.png",
  "Flint and Steel":      T+"Flint_and_Steel.png",
  "Bucket":               T+"Bucket.png",
  "Torch":                T+"Torch.png",
  "Book":                 T+"Book.png",
  "Enchanted Book":       T+"Enchanted_Book.png",
  "Bottle o' Enchanting": T+"Bottle_o'_Enchanting.png",
  "Firework Rocket":      T+"Firework_Rocket.png",
  "Wind Charge":          T+"Wind_Charge.png",
  "Mace":                 T+"Mace.png",
};
