const IMAGE_URLS = {
  // Characters
  "Mario":            "https://mario.wiki.gallery/images/thumb/0/0d/MarioAlternateJamboreeRender.png/178px-MarioAlternateJamboreeRender.png",
  "Luigi":            "https://mario.wiki.gallery/images/thumb/7/76/SMPJ_Luigi.png/174px-SMPJ_Luigi.png",
  "Princess Peach":   "https://mario.wiki.gallery/images/thumb/7/7c/Peach_Posing_Alt_3D_Artwork.png/166px-Peach_Posing_Alt_3D_Artwork.png",
  "Toad":             "https://mario.wiki.gallery/images/thumb/e/e8/Toads_SMR.png/300px-Toads_SMR.png",
  "Yoshi":            "https://mario.wiki.gallery/images/thumb/5/5f/SMPJ_Yoshi.png/181px-SMPJ_Yoshi.png",
  "Wario":            "https://mario.wiki.gallery/images/thumb/2/29/SMPWario.png/249px-SMPWario.png",
  "Waluigi":          "https://mario.wiki.gallery/images/thumb/2/27/SuperMarioParty_Waluigi.png/210px-SuperMarioParty_Waluigi.png",
  "Princess Daisy":   "https://mario.wiki.gallery/images/b/b5/Daisy_Render_MP6_2.png",
  "Rosalina":         "https://mario.wiki.gallery/images/thumb/f/f3/SMG%2BSMG2_Rosalina.png/223px-SMG%2BSMG2_Rosalina.png",
  "Bowser":           "https://mario.wiki.gallery/images/thumb/c/c7/SMBW_Artwork_Bowser.png/300px-SMBW_Artwork_Bowser.png",
  "Bowser Jr.":       "https://mario.wiki.gallery/images/thumb/f/f5/SMBW_Bowser_Jr_Artwork_1.png/300px-SMBW_Bowser_Jr_Artwork_1.png",
  "Donkey Kong":      "https://mario.wiki.gallery/images/thumb/6/6e/DKB_Thinking_DK.png/295px-DKB_Thinking_DK.png",
  "Diddy Kong":       "https://mario.wiki.gallery/images/thumb/b/b9/Diddy_2025_artwork.png/215px-Diddy_2025_artwork.png",
  "Birdo":            "https://mario.wiki.gallery/images/thumb/e/ed/MP9_Birdo_Main_Artwork.png/195px-MP9_Birdo_Main_Artwork.png",
  // Enemies
  "Goomba":           "https://mario.wiki.gallery/images/thumb/7/7d/SMBW_Goomba.png/245px-SMBW_Goomba.png",
  "Koopa Troopa":     "https://mario.wiki.gallery/images/thumb/5/5c/SuperMarioParty_KoopaTroopa.png/237px-SuperMarioParty_KoopaTroopa.png",
  "Piranha Plant":    "https://mario.wiki.gallery/images/thumb/e/e8/NSMBU_Piranha_Plant_Cropped.png/190px-NSMBU_Piranha_Plant_Cropped.png",
  "Boo":              "https://mario.wiki.gallery/images/5/58/MKW_Boo_Roulette.png",
  "Chain Chomp":      "https://mario.wiki.gallery/images/thumb/a/a9/ChainChompMP8.png/300px-ChainChompMP8.png",
  "Hammer Bro":       "https://mario.wiki.gallery/images/thumb/e/e3/NSMBU_Hammer_Bro_Artwork.png/300px-NSMBU_Hammer_Bro_Artwork.png",
  "Lakitu":           "https://mario.wiki.gallery/images/thumb/8/87/NSMBU_Lakitu_Artwork.png/231px-NSMBU_Lakitu_Artwork.png",
  "Thwomp":           "https://mario.wiki.gallery/images/thumb/3/34/NSMBU_Thwomp_Artwork.png/268px-NSMBU_Thwomp_Artwork.png",
  "Bob-omb":          "https://mario.wiki.gallery/images/2/24/MKW_Bob-omb_Roulette.png",
  "Bullet Bill":      "https://mario.wiki.gallery/images/thumb/3/36/MKW_Bullet_Bill_Roulette.png/300px-MKW_Bullet_Bill_Roulette.png",
  "Wiggler":          "https://mario.wiki.gallery/images/thumb/7/7c/WigglerDS.png/300px-WigglerDS.png",
  "Buzzy Beetle":     "https://mario.wiki.gallery/images/thumb/3/35/NSMBU_Buzzy_Beetle_Artwork.png/300px-NSMBU_Buzzy_Beetle_Artwork.png",
  "Whomp":            "https://mario.wiki.gallery/images/thumb/d/de/WhompSMP.png/300px-WhompSMP.png",
  "Cheep Cheep":      "https://mario.wiki.gallery/images/thumb/6/63/CheepCheepNSMBU.png/300px-CheepCheepNSMBU.png",
  "Blooper":          "https://mario.wiki.gallery/images/f/f8/MKW_Blooper_Roulette.png",
  "Magikoopa":        "https://mario.wiki.gallery/images/thumb/7/79/Magikoopa_Artwork_-_Super_Mario_3D_World.png/288px-Magikoopa_Artwork_-_Super_Mario_3D_World.png",
  "King Boo":         "https://mario.wiki.gallery/images/thumb/4/47/Mario_Party_Star_Rush_King_Boo.png/249px-Mario_Party_Star_Rush_King_Boo.png",
  "Dry Bones":        "https://mario.wiki.gallery/images/thumb/3/33/MPSR_Dry_Bones.png/239px-MPSR_Dry_Bones.png",
  "Spiny":            "https://mario.wiki.gallery/images/thumb/3/3e/Spiny_Artwork_-_New_Super_Mario_Bros._2.png/300px-Spiny_Artwork_-_New_Super_Mario_Bros._2.png",
  "Kamek":            "https://mario.wiki.gallery/images/thumb/3/3c/SMPJ_Kamek_Artwork.png/300px-SMPJ_Kamek_Artwork.png",
  // Power-ups
  "Super Mushroom":   "https://mario.wiki.gallery/images/thumb/a/a6/Super_Mushroom_Artwork_-_Super_Mario_3D_World.png/300px-Super_Mushroom_Artwork_-_Super_Mario_3D_World.png",
  "Fire Flower":      "https://mario.wiki.gallery/images/7/77/MKW_Fire_Flower_Roulette.png",
  "Super Star":       "https://mario.wiki.gallery/images/thumb/f/f9/MKW_Super_Star_Roulette.png/300px-MKW_Super_Star_Roulette.png",
  "Tanooki Suit":     "https://mario.wiki.gallery/images/f/fc/Tanookisuit.png",
  "Mega Mushroom":    "https://mario.wiki.gallery/images/2/26/MKW_Mega_Mushroom_Roulette.png",
  "1-Up Mushroom":    "https://mario.wiki.gallery/images/thumb/b/b4/1-Up_Mushroom_Artwork_-_Super_Mario_3D_World.png/300px-1-Up_Mushroom_Artwork_-_Super_Mario_3D_World.png",
  "Ice Flower":       "https://mario.wiki.gallery/images/7/70/MKW_Ice_Flower_Roulette.png",
  "Propeller Mushroom":"https://mario.wiki.gallery/images/thumb/c/ce/NSMBW_Propeller_Mushroom_Artwork.png/300px-NSMBW_Propeller_Mushroom_Artwork.png",
  "Penguin Suit":     "https://mario.wiki.gallery/images/thumb/e/e8/Penguinsuit.png/267px-Penguinsuit.png",
  "Frog Suit":        "https://mario.wiki.gallery/images/2/22/Frog_Mario_SMB3_art.png",
  "Cape Feather":     "https://mario.wiki.gallery/images/9/9e/MKW_Feather_Roulette.png",
  "Mini Mushroom":    "https://mario.wiki.gallery/images/thumb/a/a2/NSMBU_Mini_Mushroom_Artwork.png/300px-NSMBU_Mini_Mushroom_Artwork.png",
  // Objects
  "Question Block":   "https://mario.wiki.gallery/images/thumb/4/48/Question_Block_Artwork_-_Super_Mario_3D_World.png/300px-Question_Block_Artwork_-_Super_Mario_3D_World.png",
  "Brick Block":      "https://mario.wiki.gallery/images/1/13/SMBW_Artwork_Brick_Block.png",
  "Warp Pipe":        "https://mario.wiki.gallery/images/thumb/5/55/SMPJ_Pipe_Render.png/300px-SMPJ_Pipe_Render.png",
  "Coin":             "https://mario.wiki.gallery/images/thumb/1/10/MKW_Coin_Roulette.png/248px-MKW_Coin_Roulette.png",
  "Super Bell":       "https://mario.wiki.gallery/images/thumb/3/3e/Super_Bell_Artwork_-_Super_Mario_3D_World.png/267px-Super_Bell_Artwork_-_Super_Mario_3D_World.png",
  "Boomerang Flower": "https://mario.wiki.gallery/images/thumb/6/65/MKW_Boomerang_Flower_Roulette.png/300px-MKW_Boomerang_Flower_Roulette.png",
  "Koopa Shell":      "https://mario.wiki.gallery/images/thumb/9/94/GreenShell_-_MarioPartyStarRush.png/300px-GreenShell_-_MarioPartyStarRush.png",
  "Yoshi's Egg":      "https://mario.wiki.gallery/images/thumb/4/48/PN_Yoshi_Egg.png/281px-PN_Yoshi_Egg.png",
};
