// Animal cartoon images — Twemoji SVG emoji + Wikimedia Commons SVG illustrations
// Starfish and Dragonfly keep Wikipedia photos (no suitable SVG found)
const T = "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/";

const IMAGE_URLS = {
  // ── Mammals ───────────────────────────────────────────────────────────────
  "Lion":          T + "1f981.svg",
  "Tiger":         T + "1f42f.svg",
  "Elephant":      T + "1f418.svg",
  "Giraffe":       T + "1f992.svg",
  "Zebra":         T + "1f993.svg",
  "Leopard":       T + "1f406.svg",
  "Cheetah":       "https://upload.wikimedia.org/wikipedia/commons/4/4b/Creative-Tail-Animal-cheetah.svg",
  "Bear":          T + "1f43b.svg",
  "Wolf":          T + "1f43a.svg",
  "Fox":           T + "1f98a.svg",
  "Rabbit":        T + "1f430.svg",
  "Kangaroo":      T + "1f998.svg",
  "Giant Panda":   T + "1f43c.svg",
  "Gorilla":       T + "1f98d.svg",
  "Chimpanzee":    T + "1f412.svg",
  "Hippopotamus":  T + "1f99b.svg",
  "Rhinoceros":    T + "1f98f.svg",
  "Camel":         T + "1f42a.svg",
  "Deer":          T + "1f98c.svg",
  "Polar Bear":    T + "1f43b-200d-2744-fe0f.svg",
  // ── Birds ─────────────────────────────────────────────────────────────────
  "Eagle":         T + "1f985.svg",
  "Penguin":       T + "1f427.svg",
  "Parrot":        T + "1f99c.svg",
  "Flamingo":      T + "1f9a9.svg",
  "Peacock":       T + "1f99a.svg",
  "Owl":           T + "1f989.svg",
  "Toucan":        "https://upload.wikimedia.org/wikipedia/commons/5/56/Toucan_cartoon.svg",
  "Swan":          T + "1f9a2.svg",
  "Hummingbird":   "https://upload.wikimedia.org/wikipedia/commons/7/71/Hummingbird_-_Delapouite_-_game-icons.svg",
  "Ostrich":       "https://upload.wikimedia.org/wikipedia/commons/c/ca/Ostrich_-_Delapouite_-_game-icons.svg",
  // ── Reptiles ──────────────────────────────────────────────────────────────
  "Crocodile":     T + "1f40a.svg",
  "Snake":         T + "1f40d.svg",
  "Turtle":        T + "1f422.svg",
  "Chameleon":     "https://upload.wikimedia.org/wikipedia/commons/8/83/Chameleon_illustration.svg",
  "Iguana":        T + "1f98e.svg",
  "Komodo Dragon": "https://upload.wikimedia.org/wikipedia/commons/2/29/Komodo-dragon-animal-0035620.svg",
  // ── Sea ───────────────────────────────────────────────────────────────────
  "Dolphin":       T + "1f42c.svg",
  "Shark":         T + "1f988.svg",
  "Blue Whale":    T + "1f40b.svg",
  "Octopus":       T + "1f419.svg",
  "Jellyfish":     "https://upload.wikimedia.org/wikipedia/commons/f/fe/Cannonball_jellyfish_%281261028%29_-_The_Noun_Project.svg",
  "Seahorse":      "https://upload.wikimedia.org/wikipedia/commons/f/f0/Seahorse-no-square.svg",
  "Crab":          T + "1f980.svg",
  "Clownfish":     T + "1f420.svg",
  "Starfish":      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Starfish_montage.png/330px-Starfish_montage.png",
  // ── Insects ───────────────────────────────────────────────────────────────
  "Butterfly":     T + "1f98b.svg",
  "Bee":           T + "1f41d.svg",
  "Dragonfly":     "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Gemeine_Heidelibelle_%28Sympetrum_vulgatum%29_4.jpg/330px-Gemeine_Heidelibelle_%28Sympetrum_vulgatum%29_4.jpg",
  "Ladybug":       T + "1f41e.svg",
  "Ant":           T + "1f41c.svg",
  // ── Farm ──────────────────────────────────────────────────────────────────
  "Cow":           T + "1f404.svg",
  "Horse":         T + "1f40e.svg",
  "Pig":           T + "1f437.svg",
  "Chicken":       T + "1f414.svg",
  "Sheep":         T + "1f411.svg",
  "Goat":          T + "1f410.svg",
  "Duck":          T + "1f986.svg",
  "Donkey":        "https://upload.wikimedia.org/wikipedia/commons/2/21/Donkey_cartoon_04.svg",
};
